CREATE TABLE ROL(
ROL_ID NUMBER,
ROL_NOMBRES VARCHAR2(20) UNIQUE NOT NULL,
CONSTRAINT PK_ROL_ID PRIMARY KEY(ROL_ID),
CONSTRAINT CK_ROL_NOMBRES CHECK(ROL_NOMBRES IN('Administrador','Empleado','Repartidor'))
);

CREATE TABLE USUARIO(
USR_ID NUMBER,
USR_NOMBRES VARCHAR2(100) NOT NULL,
USR_APELLIDOS VARCHAR2(100) NOT NULL,
USR_CORREOS VARCHAR2(150) UNIQUE NOT NULL,
USR_CONTRASENIAS VARCHAR2(310) NOT NULL,
USR_TOKEN_RECUPERACIONES VARCHAR2(6),
USR_TOKEN_EXPIRACIONES DATE,
ROL_ID NUMBER NOT NULL,
CONSTRAINT PK_USR_ID PRIMARY KEY(USR_ID),
CONSTRAINT FK_ROL_USR FOREIGN KEY(ROL_ID) REFERENCES ROL(ROL_ID)
);

CREATE SEQUENCE SEQ_USUARIO START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ENCOMENDISTA(
ENC_ID NUMBER,
ENC_NOMBRES VARCHAR2(50) NOT NULL,
ENC_CONTACTOS VARCHAR2(150) NOT NULL,
CONSTRAINT PK_ENC_ID PRIMARY KEY(ENC_ID)
);
COMMENT ON COLUMN ENCOMENDISTA.ENC_ID IS 'Llave primaria';
COMMENT ON COLUMN ENCOMENDISTA.ENC_NOMBRES IS 'Nombre del encomendista';
COMMENT ON COLUMN ENCOMENDISTA.ENC_CONTACTOS IS 'Contacto';
 

CREATE SEQUENCE SEQ_ENCOMENDISTA START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE UBICACION(
UBI_ID NUMBER,
UBI_DEPARTAMENTOS VARCHAR2(15) NOT NULL,
UBI_MUNICIPIOS VARCHAR2(25) NOT NULL,
UBI_DIAS VARCHAR2(24) NOT NULL,
UBI_HORARIOS VARCHAR2(32) NOT NULL,
ENC_ID NUMBER NOT NULL,
UBI_DIRECCIONES VARCHAR2(300) NOT NULL,
UBI_PRECIOS_ENVIOS NUMBER(8,2),
UBI_OBSERVACIONES VARCHAR2(300),
CONSTRAINT PK_UBI_ID PRIMARY KEY(UBI_ID),
CONSTRAINT FK_ENC_UBI FOREIGN KEY(ENC_ID) REFERENCES ENCOMENDISTA(ENC_ID),
CONSTRAINT CK_DIAS_UBI CHECK(UBI_DIAS IN('Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'))
);

CREATE SEQUENCE SEQ_UBICACION START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE EVENTO(
EVE_ID NUMBER,
EVE_NOMBRES VARCHAR2(50) NOT NULL,
EVE_IMGS VARCHAR2(500),
EVE_ORGANIZADORES VARCHAR2(300) NOT NULL,
UBI_ID NUMBER NOT NULL,
EVE_FECHAS DATE NOT NULL,
CONSTRAINT PK_EVE_ID PRIMARY KEY(EVE_ID),
CONSTRAINT FK_UBI_EVE FOREIGN KEY(UBI_ID) REFERENCES UBICACION(UBI_ID)
);

CREATE SEQUENCE SEQ_EVENTO START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CLIENTE(
CLI_ID NUMBER,
CLI_NOMBRES VARCHAR2(100) NOT NULL,
CLI_APELLIDOS VARCHAR2(100) NOT NULL,
CLI_NUMEROS VARCHAR2(24) CHECK(REGEXP_LIKE(CLI_NUMEROS,'^[0-9]{4}-[0-9]{4}$')) NOT NULL,
CLI_CONTACTO_ADICIONALES VARCHAR2(150),
CLI_FECHA_NACIMIENTOS DATE NOT NULL,
CLI_TIPO_CLIENTES VARCHAR2(30),
CONSTRAINT PK_CLI_ID PRIMARY KEY(CLI_ID),
CONSTRAINT CK_TIPO CHECK(CLI_TIPO_CLIENTES IN('Cliente Red Social','Cliente App'))
);

CREATE SEQUENCE SEQ_CLIENTE START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE UBICACION_CLIENTE(
UBC_ID NUMBER,
UBI_ID NUMBER,
CLI_ID NUMBER,
CONSTRAINT PK_UBC_ID PRIMARY KEY(UBC_ID),
CONSTRAINT FK_UBI_UBC FOREIGN KEY(UBI_ID) REFERENCES UBICACION(UBI_ID),
CONSTRAINT FK_CLI_UBC FOREIGN KEY(CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE SEQUENCE SEQ_UBICACION_CLIENTE START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CREDENCIAL_CLIENTE(
CRC_ID RAW(16) DEFAULT SYS_GUID(),
CRC_CONTRASENIAS VARCHAR2(310) NOT NULL,
CRC_CORREOS VARCHAR2(150) UNIQUE NOT NULL,
CRC_TOKENS VARCHAR2(6),
CRC_TOKEN_EXPIRACIONES DATE,
CLI_ID NUMBER NOT NULL,
CONSTRAINT PK_CRC_ID PRIMARY KEY(CRC_ID),
CONSTRAINT FK_CLI_CRC FOREIGN KEY(CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE MATERIAL(
MTR_ID NUMBER,
MTR_NOMBRES VARCHAR2(100) UNIQUE NOT NULL,
CONSTRAINT PK_MTR_ID PRIMARY KEY(MTR_ID)
);

CREATE SEQUENCE SEQ_MATERIAL START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE CATEGORIA_ROPA(
CTR_ID NUMBER,
CTR_NOMBRES VARCHAR2(100) UNIQUE NOT NULL,
CONSTRAINT PK_CTR_ID PRIMARY KEY(CTR_ID)
);

CREATE SEQUENCE SEQ_CATEGORIA_ROPA START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE CATEGORIA_TEMATICA(
CTT_ID NUMBER,
CTT_NOMBRES VARCHAR2(100) UNIQUE NOT NULL,
CONSTRAINT PK_CTT_ID PRIMARY KEY(CTT_ID)
);

CREATE SEQUENCE SEQ_CATEGORIA_TEMATICA START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE SEQUENCE SEQ_TALLA START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE PRODUCTO(
PRO_ID NUMBER,
PRO_NOMBRES VARCHAR2(150) NOT NULL,
PRO_DESCRIPCIONES VARCHAR2(350) NOT NULL,
PRO_STOCK NUMBER CHECK(PRO_STOCK>=0) NOT NULL,
PRO_PRECIO_UNIDADES NUMBER(10,2) CHECK(PRO_PRECIO_UNIDADES>=0) NOT NULL,
PRO_DESCUENTOS NUMBER(10,2) DEFAULT 0 CHECK(PRO_DESCUENTOS>=0) NOT NULL,
PRO_ESTADOS VARCHAR2(24) NOT NULL,
CTR_ID NUMBER,
MTR_ID NUMBER NOT NULL,
PRO_IMG VARCHAR2(500),
CONSTRAINT PK_PRO_ID PRIMARY KEY(PRO_ID),
CONSTRAINT FK_CTR_PRO FOREIGN KEY(CTR_ID) REFERENCES CATEGORIA_ROPA(CTR_ID),
CONSTRAINT FK_MTR_PRO FOREIGN KEY(MTR_ID) REFERENCES MATERIAL(MTR_ID) ,
CONSTRAINT CK_ESTADOS CHECK(PRO_ESTADOS IN('Activo','Inactivo'))
);

CREATE SEQUENCE SEQ_PRODUCTO START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DETALLE_CATEGORIA_TEMATICA_PRODUCTO(
DCT_ID NUMBER,
CTT_ID NUMBER,
PRO_ID NUMBER,
CONSTRAINT PK_DCT_ID PRIMARY KEY(DCT_ID),
CONSTRAINT FK_CTT_DCT FOREIGN KEY(CTT_ID) REFERENCES CATEGORIA_TEMATICA(CTT_ID) ,
CONSTRAINT FK_PRO_DCT FOREIGN KEY(PRO_ID) REFERENCES PRODUCTO(PRO_ID) 
);

CREATE SEQUENCE SEQ_DCT START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE PRODUCTO_GUARDADO(
PRG_ID NUMBER,
PRO_ID NUMBER NOT NULL,
CLI_ID NUMBER NOT NULL,
CONSTRAINT PK_PRG_ID PRIMARY KEY(PRG_ID),
CONSTRAINT FK_PRO_PRG FOREIGN KEY(PRO_ID) REFERENCES PRODUCTO(PRO_ID),
CONSTRAINT FK_CLI_PRG FOREIGN KEY(CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE SEQUENCE SEQ_PRODUCTO_GUARDADO START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE PEDIDO(
PED_ID NUMBER,
PED_FECHAS DATE,
PED_PRECIO_TOTALES NUMBER(10,2) DEFAULT 0 CHECK(PED_PRECIO_TOTALES>=0) NOT NULL,
PED_TOTAL_DESCUENTOS NUMBER(10,2) DEFAULT 0 CHECK(PED_TOTAL_DESCUENTOS>=0) NOT NULL,
PED_ESTADO_COMPRAS VARCHAR2(24) NOT NULL,
PED_TOTAL_FINALES NUMBER(10,2) DEFAULT 0 CHECK(PED_TOTAL_FINALES>=0) NOT NULL,
PED_CODIGO_TRANSFERENCIAS VARCHAR2(250),
UBC_ID NUMBER NOT NULL,
USR_ID NUMBER NOT NULL,
CONSTRAINT UQ_PED_CODIGO UNIQUE(PED_CODIGO_TRANSFERENCIAS),
CONSTRAINT CK_PED_ESTADO CHECK(PED_ESTADO_COMPRAS IN('Carrito','Pendiente','Aprobado','Entregado')),
CONSTRAINT PK_PED_ID PRIMARY KEY(PED_ID),
CONSTRAINT FK_UBC_PED FOREIGN KEY(UBC_ID) REFERENCES UBICACION_CLIENTE(UBC_ID) ,
CONSTRAINT FK_USR_PED FOREIGN KEY(USR_ID) REFERENCES USUARIO(USR_ID) 
);

CREATE SEQUENCE SEQ_PEDIDO START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DETALLE_PEDIDO(
DTP_ID NUMBER,
PRO_ID NUMBER NOT NULL,
PED_ID NUMBER NOT NULL,
DTP_TALLA_PRENDAS VARCHAR2(10)NOT NULL,
DTP_CANTIDADES NUMBER CHECK(DTP_CANTIDADES>0) NOT NULL,
CONSTRAINT PK_DTP_ID PRIMARY KEY(DTP_ID),
CONSTRAINT FK_PRO_DTP FOREIGN KEY(PRO_ID) REFERENCES PRODUCTO(PRO_ID),
CONSTRAINT FK_PED_DTP FOREIGN KEY(PED_ID) REFERENCES PEDIDO(PED_ID),
CONSTRAINT CK_DTP_TALLA_PRENDAS CHECK(DTP_TALLA_PRENDAS IN('XXS','XS','S','M','L','XL','XXL'))
);

CREATE SEQUENCE SEQ_DETALLE_PEDIDO START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Comentarios*/
COMMENT ON COLUMN ROL.ROL_ID IS 'Llave primaria de la tabla rol';
COMMENT ON COLUMN ROL.ROL_NOMBRES IS 'Nombre del rol dentro del sistema';

COMMENT ON COLUMN USUARIO.USR_ID IS 'Llave primaria de la tabla usuario';
COMMENT ON COLUMN USUARIO.USR_NOMBRES IS 'Nombres del usuario';
COMMENT ON COLUMN USUARIO.USR_APELLIDOS IS 'Apellidos del usuario';
COMMENT ON COLUMN USUARIO.USR_CORREOS IS 'Correo electronico del usuario';
COMMENT ON COLUMN USUARIO.USR_CONTRASENIAS IS 'Contraseña cifrada del usuario';
COMMENT ON COLUMN USUARIO.USR_TOKEN_RECUPERACIONES IS 'Token utilizado para recuperacion de contraseña';
COMMENT ON COLUMN USUARIO.USR_TOKEN_EXPIRACIONES IS 'Fecha y hora de expiracion del token';
COMMENT ON COLUMN USUARIO.ROL_ID IS 'Llave foranea hacia la tabla rol';

COMMENT ON COLUMN ENCOMENDISTA.ENC_ID IS 'Llave primaria de la tabla encomendista';
COMMENT ON COLUMN ENCOMENDISTA.ENC_NOMBRES IS 'Nombre del encomendista';
COMMENT ON COLUMN ENCOMENDISTA.ENC_CONTACTOS IS 'Informacion de contacto del encomendista';

COMMENT ON COLUMN UBICACION.UBI_ID IS 'Llave primaria de la tabla ubicacion';
COMMENT ON COLUMN UBICACION.UBI_DEPARTAMENTOS IS 'Departamento de entrega';
COMMENT ON COLUMN UBICACION.UBI_MUNICIPIOS IS 'Municipio de entrega';
COMMENT ON COLUMN UBICACION.UBI_DIAS IS 'Dia disponible para entregas';
COMMENT ON COLUMN UBICACION.UBI_HORARIOS IS 'Horario disponible de entrega';
COMMENT ON COLUMN UBICACION.ENC_ID IS 'Llave foranea hacia la tabla encomendista';
COMMENT ON COLUMN UBICACION.UBI_DIRECCIONES IS 'Direccion exacta de entrega';
COMMENT ON COLUMN UBICACION.UBI_PRECIOS_ENVIOS IS 'Costo de envio';
COMMENT ON COLUMN UBICACION.UBI_OBSERVACIONES IS 'Observaciones adicionales de entrega';

COMMENT ON COLUMN EVENTO.EVE_ID IS 'Llave primaria de la tabla evento';
COMMENT ON COLUMN EVENTO.EVE_NOMBRES IS 'Nombre del evento';
COMMENT ON COLUMN EVENTO.EVE_IMGS IS 'Ruta o URL de la imagen del evento';
COMMENT ON COLUMN EVENTO.EVE_ORGANIZADORES IS 'Nombre de los organizadores del evento';
COMMENT ON COLUMN EVENTO.UBI_ID IS 'Llave foranea hacia la tabla ubicacion';

COMMENT ON COLUMN CLIENTE.CLI_ID IS 'Llave primaria de la tabla cliente';
COMMENT ON COLUMN CLIENTE.CLI_NOMBRES IS 'Nombres del cliente';
COMMENT ON COLUMN CLIENTE.CLI_APELLIDOS IS 'Apellidos del cliente';
COMMENT ON COLUMN CLIENTE.CLI_NUMEROS IS 'Numero telefonico del cliente';
COMMENT ON COLUMN CLIENTE.CLI_CONTACTO_ADICIONALES IS 'Informacion adicional de contacto';
COMMENT ON COLUMN CLIENTE.CLI_FECHA_NACIMIENTOS IS 'Fecha de nacimiento del cliente';
COMMENT ON COLUMN CLIENTE.CLI_TIPO_CLIENTES IS 'Tipo de cliente registrado';

COMMENT ON COLUMN UBICACION_CLIENTE.UBC_ID IS 'Llave primaria de la tabla ubicacion_cliente';
COMMENT ON COLUMN UBICACION_CLIENTE.UBI_ID IS 'Llave foranea hacia la tabla ubicacion';
COMMENT ON COLUMN UBICACION_CLIENTE.CLI_ID IS 'Llave foranea hacia la tabla cliente';

COMMENT ON COLUMN CREDENCIAL_CLIENTE.CRC_ID IS 'Llave primaria de la tabla credencial_cliente';
COMMENT ON COLUMN CREDENCIAL_CLIENTE.CRC_CONTRASENIAS IS 'Contraseña cifrada del cliente';
COMMENT ON COLUMN CREDENCIAL_CLIENTE.CRC_CORREOS IS 'Correo electronico del cliente';
COMMENT ON COLUMN CREDENCIAL_CLIENTE.CRC_TOKENS IS 'Token utilizado para recuperacion de acceso';
COMMENT ON COLUMN CREDENCIAL_CLIENTE.CRC_TOKEN_EXPIRACIONES IS 'Fecha y hora de expiracion del token';
COMMENT ON COLUMN CREDENCIAL_CLIENTE.CLI_ID IS 'Llave foranea hacia la tabla cliente';

COMMENT ON COLUMN MATERIAL.MTR_ID IS 'Llave primaria de la tabla material';
COMMENT ON COLUMN MATERIAL.MTR_NOMBRES IS 'Nombre del material';

COMMENT ON COLUMN CATEGORIA_ROPA.CTR_ID IS 'Llave primaria de la tabla categoria_ropa';
COMMENT ON COLUMN CATEGORIA_ROPA.CTR_NOMBRES IS 'Nombre de la categoria de ropa';
COMMENT ON COLUMN CATEGORIA_TEMATICA.CTT_ID IS 'Llave primaria de la tabla categoria_tematica';
COMMENT ON COLUMN CATEGORIA_TEMATICA.CTT_NOMBRES IS 'Nombre de la categoria tematica';

COMMENT ON COLUMN PRODUCTO.PRO_ID IS 'Llave primaria de la tabla producto';
COMMENT ON COLUMN PRODUCTO.PRO_NOMBRES IS 'Nombre del producto';
COMMENT ON COLUMN PRODUCTO.PRO_DESCRIPCIONES IS 'Descripcion del producto';
COMMENT ON COLUMN PRODUCTO.PRO_STOCK IS 'Cantidad disponible en inventario';
COMMENT ON COLUMN PRODUCTO.PRO_PRECIO_UNIDADES IS 'Precio unitario del producto';
COMMENT ON COLUMN PRODUCTO.PRO_DESCUENTOS IS 'Descuento aplicado al producto';
COMMENT ON COLUMN PRODUCTO.PRO_ESTADOS IS 'Estado actual del producto';
COMMENT ON COLUMN PRODUCTO.CTR_ID IS 'Llave foranea hacia la tabla categoria_ropa';
COMMENT ON COLUMN PRODUCTO.MTR_ID IS 'Llave foranea hacia la tabla material';
COMMENT ON COLUMN PRODUCTO.PRO_IMG IS 'Ruta o URL de la imagen del producto';

COMMENT ON COLUMN DETALLE_CATEGORIA_TEMATICA_PRODUCTO.DCT_ID IS 'Llave primaria de la tabla detalle_categoria_tematica_producto';
COMMENT ON COLUMN DETALLE_CATEGORIA_TEMATICA_PRODUCTO.CTT_ID IS 'Llave foranea hacia la tabla categoria_tematica';
COMMENT ON COLUMN DETALLE_CATEGORIA_TEMATICA_PRODUCTO.PRO_ID IS 'Llave foranea hacia la tabla producto';

COMMENT ON COLUMN PRODUCTO_GUARDADO.PRG_ID IS 'Llave primaria de la tabla producto_guardado';
COMMENT ON COLUMN PRODUCTO_GUARDADO.PRO_ID IS 'Llave foranea hacia la tabla producto';
COMMENT ON COLUMN PRODUCTO_GUARDADO.CLI_ID IS 'Llave foranea hacia la tabla cliente';

COMMENT ON COLUMN PEDIDO.PED_ID IS 'Llave primaria de la tabla pedido';
COMMENT ON COLUMN PEDIDO.PED_FECHAS IS 'Fecha programada de entrega';
COMMENT ON COLUMN PEDIDO.PED_PRECIO_TOTALES IS 'Subtotal acumulado del pedido';
COMMENT ON COLUMN PEDIDO.PED_TOTAL_DESCUENTOS IS 'Total de descuentos aplicados';
COMMENT ON COLUMN PEDIDO.PED_ESTADO_COMPRAS IS 'Estado actual del pedido';
COMMENT ON COLUMN PEDIDO.PED_TOTAL_FINALES IS 'Monto final a pagar';
COMMENT ON COLUMN PEDIDO.PED_CODIGO_TRANSFERENCIAS IS 'Codigo de comprobante de transferencia';
COMMENT ON COLUMN PEDIDO.UBC_ID IS 'Llave foranea hacia la tabla ubicacion_cliente';
COMMENT ON COLUMN PEDIDO.USR_ID IS 'Llave foranea hacia la tabla usuario';

COMMENT ON COLUMN DETALLE_PEDIDO.DTP_ID IS 'Llave primaria de la tabla detalle_pedido';
COMMENT ON COLUMN DETALLE_PEDIDO.PRO_ID IS 'Llave foranea hacia la tabla producto';
COMMENT ON COLUMN DETALLE_PEDIDO.PED_ID IS 'Llave foranea hacia la tabla pedido';
COMMENT ON COLUMN DETALLE_PEDIDO.DTP_CANTIDADES IS 'Cantidad de productos solicitados';
COMMENT ON COLUMN DETALLE_PEDIDO.DTP_TALLA_PRENDAS IS 'Talla de las prendas que el cliente solicito';
/*Triggers*/
/*Trigger para verificar que la fecha del evento no sea una fecha pasada*/
CREATE OR REPLACE TRIGGER TRG_FECHA_EVE
BEFORE INSERT OR UPDATE ON EVENTO
FOR EACH ROW
BEGIN
IF :NEW.EVE_FECHAS<TRUNC(SYSDATE) THEN
RAISE_APPLICATION_ERROR(-20008,'La fecha no puede ser menor que la actual');
END IF;
END;
/
 
 
/*Trigger para verificar que la fecha que se entregara el pedido no sea una fecha pasada*/
CREATE OR REPLACE TRIGGER TRG_FECHA_PED
BEFORE INSERT OR UPDATE ON PEDIDO
FOR EACH ROW
BEGIN
IF :NEW.PED_FECHAS<TRUNC(SYSDATE) THEN
RAISE_APPLICATION_ERROR(-20008,'La fecha no puede ser menor que la actual');
END IF;
END;
/
/*Trigger para verificar que no se pueda realizar un insert de detalle pedido a un pedido que no tenga el estado de carrito*/
CREATE OR REPLACE TRIGGER TRG_INSERT_DETALLE_PEDIDO
BEFORE INSERT ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
V_ESTADO PEDIDO.PED_ESTADO_COMPRAS%TYPE;
V_STOCK PRODUCTO.PRO_STOCK%TYPE;
BEGIN
SELECT PED_ESTADO_COMPRAS
INTO V_ESTADO
FROM PEDIDO
WHERE PED_ID=:NEW.PED_ID;
IF V_ESTADO<>'Carrito' THEN
RAISE_APPLICATION_ERROR(-20012,'Solo se pueden agregar productos en carrito');
END IF;
SELECT PRO_STOCK
INTO V_STOCK
FROM PRODUCTO
WHERE PRO_ID=:NEW.PRO_ID;
IF :NEW.DTP_CANTIDADES>V_STOCK THEN
RAISE_APPLICATION_ERROR(-20002,'La cantidad supera el stock disponible');
END IF;
END;
/
/*Trigger para aumentar al total del pedido cuando se añado un producto (en este caso un registro de detalle pedido)*/
CREATE OR REPLACE TRIGGER TRG_INSERT_TOTAL_PEDIDO
AFTER INSERT ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
V_PRECIO PRODUCTO.PRO_PRECIO_UNIDADES%TYPE;
V_DESCUENTO PRODUCTO.PRO_DESCUENTOS%TYPE;
BEGIN
SELECT PRO_PRECIO_UNIDADES,PRO_DESCUENTOS
INTO V_PRECIO,V_DESCUENTO
FROM PRODUCTO
WHERE PRO_ID=:NEW.PRO_ID;
UPDATE PEDIDO
SET PED_PRECIO_TOTALES=PED_PRECIO_TOTALES+(V_PRECIO*:NEW.DTP_CANTIDADES),
PED_TOTAL_DESCUENTOS=PED_TOTAL_DESCUENTOS+(V_DESCUENTO*:NEW.DTP_CANTIDADES),
PED_TOTAL_FINALES=PED_TOTAL_FINALES+((V_PRECIO-V_DESCUENTO)*:NEW.DTP_CANTIDADES)
WHERE PED_ID=:NEW.PED_ID;
END;
/
/*Trigger para verificar que no se pueda actualizar informacion de detalle pedido si el estado de compras no es carrito*/
CREATE OR REPLACE TRIGGER TRG_VALIDAR_UPDATE_DETALLE
BEFORE UPDATE ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
V_ESTADO PEDIDO.PED_ESTADO_COMPRAS%TYPE;
V_STOCK PRODUCTO.PRO_STOCK%TYPE;
V_DIFERENCIA NUMBER;
BEGIN
SELECT PED_ESTADO_COMPRAS
INTO V_ESTADO
FROM PEDIDO
WHERE PED_ID=:OLD.PED_ID;
IF V_ESTADO<>'Carrito' THEN
RAISE_APPLICATION_ERROR(-20013,'Solo se puede modificar en carrito');
END IF;
SELECT PRO_STOCK
INTO V_STOCK
FROM PRODUCTO
WHERE PRO_ID=:OLD.PRO_ID;
V_DIFERENCIA:=:NEW.DTP_CANTIDADES-:OLD.DTP_CANTIDADES;
IF V_DIFERENCIA>V_STOCK THEN
RAISE_APPLICATION_ERROR(-20004,'Stock insuficiente');
END IF;
END;
/
/*Trigger para actualizar el total a pagar de un pedido si se añaden mas productos del mismo tipo*/
CREATE OR REPLACE TRIGGER TRG_UPDATE_TOTAL_PEDIDO
AFTER UPDATE ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
V_PRECIO PRODUCTO.PRO_PRECIO_UNIDADES%TYPE;
V_DESCUENTO PRODUCTO.PRO_DESCUENTOS%TYPE;
BEGIN
SELECT PRO_PRECIO_UNIDADES,PRO_DESCUENTOS
INTO V_PRECIO,V_DESCUENTO
FROM PRODUCTO
WHERE PRO_ID=:NEW.PRO_ID;
UPDATE PEDIDO
SET PED_PRECIO_TOTALES=PED_PRECIO_TOTALES-(V_PRECIO*:OLD.DTP_CANTIDADES)+(V_PRECIO*:NEW.DTP_CANTIDADES),
PED_TOTAL_DESCUENTOS=PED_TOTAL_DESCUENTOS-(V_DESCUENTO*:OLD.DTP_CANTIDADES)+(V_DESCUENTO*:NEW.DTP_CANTIDADES),
PED_TOTAL_FINALES=PED_TOTAL_FINALES-((V_PRECIO-V_DESCUENTO)*:OLD.DTP_CANTIDADES)+((V_PRECIO-V_DESCUENTO)*:NEW.DTP_CANTIDADES)
WHERE PED_ID=:NEW.PED_ID;
END;
/
/*Trigger para validar que no se pueda eliminar un producto de detalle producto si el estado de compra es igual a carrito*/
CREATE OR REPLACE TRIGGER TRG_VALIDAR_DELETE_DETALLE
BEFORE DELETE ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
V_ESTADO PEDIDO.PED_ESTADO_COMPRAS%TYPE;
BEGIN
SELECT PED_ESTADO_COMPRAS
INTO V_ESTADO
FROM PEDIDO
WHERE PED_ID=:OLD.PED_ID;
IF V_ESTADO<>'Carrito' THEN
RAISE_APPLICATION_ERROR(-20011,'Solo se puede eliminar en carrito');
END IF;
END;
/
/*Trigger para eliminar porcentaje del total a pagar si se elimina un producto de detalle pedido*/
CREATE OR REPLACE TRIGGER TRG_DELETE_TOTAL_PEDIDO
AFTER DELETE ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
V_PRECIO PRODUCTO.PRO_PRECIO_UNIDADES%TYPE;
V_DESCUENTO PRODUCTO.PRO_DESCUENTOS%TYPE;
BEGIN
SELECT PRO_PRECIO_UNIDADES,PRO_DESCUENTOS
INTO V_PRECIO,V_DESCUENTO
FROM PRODUCTO
WHERE PRO_ID=:OLD.PRO_ID;
UPDATE PEDIDO
SET PED_PRECIO_TOTALES=PED_PRECIO_TOTALES-(V_PRECIO*:OLD.DTP_CANTIDADES),
PED_TOTAL_DESCUENTOS=PED_TOTAL_DESCUENTOS-(V_DESCUENTO*:OLD.DTP_CANTIDADES),
PED_TOTAL_FINALES=PED_TOTAL_FINALES-((V_PRECIO-V_DESCUENTO)*:OLD.DTP_CANTIDADES)
WHERE PED_ID=:OLD.PED_ID;
END;
/
/*Trigger para descontar stock al aprovarse una venta*/
CREATE OR REPLACE TRIGGER TRG_DESCONTAR_STOCK
AFTER UPDATE OF PED_ESTADO_COMPRAS ON PEDIDO
FOR EACH ROW
DECLARE
V_STOCK PRODUCTO.PRO_STOCK%TYPE;
BEGIN
IF :OLD.PED_ESTADO_COMPRAS<>'Aprobado'
AND :NEW.PED_ESTADO_COMPRAS='Aprobado' THEN
FOR V_DETALLE IN(
SELECT PRO_ID,DTP_CANTIDADES
FROM DETALLE_PEDIDO
WHERE PED_ID=:NEW.PED_ID
)
LOOP
SELECT PRO_STOCK
INTO V_STOCK
FROM PRODUCTO
WHERE PRO_ID=V_DETALLE.PRO_ID;
IF V_DETALLE.DTP_CANTIDADES>V_STOCK THEN
RAISE_APPLICATION_ERROR(-20006,'Stock insuficiente para aprobar el pedido');
END IF;
UPDATE PRODUCTO
SET PRO_STOCK=PRO_STOCK-V_DETALLE.DTP_CANTIDADES
WHERE PRO_ID=V_DETALLE.PRO_ID;
END LOOP;
END IF;
END;
/
