ALTER SESSION SET CONTAINER = XEPDB1;
CREATE TABLESPACE PTCPRUEBAS DATAFILE 'VLADIMIR_2023042221.dbf' SIZE 50M AUTOEXTEND ON
CREATE USER PTCPRUEBAS IDENTIFIED BY 12345
DEFAULT TABLESPACE ptcpruebas TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO PTCPRUEBAs;
GRANT ALL PRIVILEGES TO PTCPRUEBAs;