ALTER SESSION SET CONTAINER =XEPDB1;

DROP TABLESPACE DB_PTC30 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE DB_PTC30 DATAFILE 'DB_PTC30.dbf' SIZE 50M AUTOEXTEND ON;
CREATE USER Soft_Bear IDENTIFIED BY 1234
DEFAULT TABLESPACE DB_PTC30
TEMPORARY TABLESPACE TEMP;

--ASIGNAR ROL
GRANT CONNECT TO Soft_Bear;-->PERMISO PARA PODER CREAR UNA CONEXION
GRANT ALL PRIVILEGES TO Soft_Bear;-->PERMISOS PARA PODER HACER TODO EN LA BASE DE DATOS
