ALTER SESSION SET CONTAINER = XEPDB1;
CREATE TABLESPACE PTCPRUEBAONE DATAFILE 'VLADIMIR___.dbf' SIZE 50M AUTOEXTEND ON
CREATE USER PTCPRUEBASONE IDENTIFIED BY 12345
DEFAULT TABLESPACE ptcpruebaone TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO PTCPRUEBASONE;
GRANT ALL PRIVILEGES TO PTCPRUEBAsONE;