CREATE TABLE ROL(
ROL_id NUMBER,
ROL_nombres VARCHAR2(20) UNIQUE NOT NULL,
CONSTRAINT PK_ROL_ID PRIMARY KEY(ROL_id),
CONSTRAINT NOMBRESROL CHECK(ROL_nombres IN ('Administrador','Empleado','Repartidor'))
);

COMMENT ON COLUMN ROL.ROL_ID IS 'Llave primaria de la tabla rol';
COMMENT ON COLUMN ROL.ROL_NOMBRES IS 'Nomnbre interno que tendra el rol dentro del sistema';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO ROL
VALUES (SEQ_ROL.NEXTVAL, 'Administrador');

CREATE TABLE USUARIO(
USR_ID NUMBER,
USR_NOMBRES VARCHAR2(100) NOT NULL,
USR_APELLIDOS VARCHAR2(100) NOT NULL,
USR_CORREOS VARCHAR2(150) UNIQUE NOT NULL,
USR_CONTRASENIAS VARCHAR2(264) NOT NULL,
USR_TOKEN_RECUPERACION VARCHAR2(6)NULL,
USR_TOKEN_EXPIRACION DATE,
ROL_ID NUMBER NOT NULL,

CONSTRAINT PK_USR_ID PRIMARY KEY (USR_ID),
CONSTRAINT FK_ROL_USR FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN USUARIO.USR_ID IS 'Llave primaria de la tabla usuario';
COMMENT ON COLUMN USUARIO.USR_NOMBRES IS 'Nombre del usuario';
COMMENT ON COLUMN USUARIO.USR_APELLIDOS IS 'Apellidos del usuario';
COMMENT ON COLUMN USUARIO.USR_CORREOS IS 'Correo electronico del usuario, sera nesesesario para que pueda iniciar sesion';
COMMENT ON COLUMN USUARIO.USR_CONTRASENIAS IS 'Contraseña unica que tendra el usuario';
COMMENT ON COLUMN USUARIO.USR_TOKEN_RECUPERACION IS 'Token de recuperacion de cuenta';
COMMENT ON COLUMN USUARIO.USR_TOKEN_EXPIRACION IS 'Tiempo de duracion del token de recuperacion';
COMMENT ON COLUMN USUARIO.ROL_ID IS 'Llave foranea a la tabla rol';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO USUARIO
VALUES( SEQ_USUARIO.NEXTVAL, 'Juan', 'Perez', 'juanperez@gmail.com', '123456', NULL, NULL, 1
);

CREATE TABLE ENCOMENDISTA(
ENC_ID NUMBER,
ENC_NOMBRES VARCHAR2(50) NOT NULL,
ENC_CONTACTOS VARCHAR2(150) NOT NULL,

CONSTRAINT PK_ENC_ID PRIMARY KEY (ENC_ID)
);

COMMENT ON COLUMN ENCOMENDISTA.ENC_ID IS 'Llave primaria de la tabla encomendista';
COMMENT ON COLUMN ENCOMENDISTA.ENC_NOMBRES IS 'Nombre de la empresa o entidad que funciona como encomendista';
COMMENT ON COLUMN ENCOMENDISTA.ENC_CONTACTOS IS 'Contacto de el encomendista';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_ENCOMENDISTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO ENCOMENDISTA
VALUES( SEQ_ENCOMENDISTA.NEXTVAL, 'Carlos Mendoza', '7254-8899' );

CREATE TABLE UBICACION (
UBI_ID NUMBER,
UBI_DEPARTAMENTOS VARCHAR2(15)NOT NULL,
UBI_MUNICIPIOS VARCHAR2(25) NOT NULL,
UBI_FECHAS DATE NOT NULL,
UBI_HORARIOS VARCHAR2(15) NOT NULL,
ENC_ID NUMBER NOT NULL,
UBI_DIRECCIONES VARCHAR2(300) NOT NULL,
UBI_PRECIOS_ENVIOS NUMBER(8,2),
UBI_OBSERVACIONES VARCHAR(300),

CONSTRAINT PK_UBI_ID PRIMARY KEY (UBI_ID),
CONSTRAINT FK_ENC_UBI FOREIGN KEY (ENC_ID) REFERENCES ENCOMENDISTA(ENC_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN UBICACION.UBI_ID IS 'Llave primaria de la tabla Ubicacion';
COMMENT ON COLUMN UBICACION.UBI_DEPARTAMENTOS IS 'Departamento em el que se encuentra la direccion ';
COMMENT ON COLUMN UBICACION.UBI_MUNICIPIOS IS 'Municipio en el que se encuentra la direccion';
COMMENT ON COLUMN UBICACION.UBI_FECHAS IS 'Fecha en que se realizan entregas en esa ubicacion';
COMMENT ON COLUMN UBICACION.UBI_HORARIOS IS 'Hora y detalles';
COMMENT ON COLUMN UBICACION.ENC_ID IS ' Llave foranea a la tabla encomendista,En caso que en la direccion un encomendista realice la entrega';
COMMENT ON COLUMN UBICACION.UBI_DIRECCIONES IS 'Direccion de la ubicacion de entrega';
COMMENT ON COLUMN UBICACION.PRECIOS_ENVIOS IS 'Precio del envio';
COMMENT ON COLUMN UBICACION.UBI_OBSERVACIONES IS 'Observaciones sobre el lugar de entrega';


/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_UBICACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO UBICACION
VALUES( SEQ_UBICACION.NEXTVAL, 'San Salvador', 'Soyapango', TO_DATE('2026-05-06','YYYY-MM-DD'), '08:00 AM', 1, 'Colonia Las Flores, Calle Principal #15' );

CREATE TABLE EVENTO(
EVE_ID NUMBER,
EVE_NOMBRES VARCHAR2(50) NOT NULL,  
EVE_IMGS VARCHAR2 (500),
EVE_ORGANIZADORES VARCHAR2(300) NOT NULL,
UBI_ID NUMBER NOT NULL,

CONSTRAINT PK_EVE_ID PRIMARY KEY(EVE_ID),
CONSTRAINT FK_UBI_EVE FOREIGN KEY (UBI_ID) REFERENCES UBICACION(UBI_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN EVENTO.EVE_ID IS 'Llave primaria de la tabla Evento';
COMMENT ON COLUMN EVENTO.EVE_NOMBRES IS 'Nombre del evento';
COMMENT ON COLUMN EVENTO.EVE_IMGS IS 'Espacio para la imagen promocional del evento';
COMMENT ON COLUMN EVENTO.EVE_ORGANIZADORES IS 'Quienes son los organizadores del evento, ejemplo: El evento es terror cifco, el organizador es cifco';
COMMENT ON COLUMN EVENTO.UBI_ID IS 'Llave foranea a la tabla ubicacion';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_EVENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO EVENTO
VALUES( SEQ_EVENTO.NEXTVAL, 'Anime Fest 2026', 'https://animefest.com/img/evento.jpg', 'Otaku Organization El Salvador', 1 );

CREATE TABLE CLIENTE(
CLI_ID NUMBER,
CLI_NOMBRES VARCHAR2(100) NOT NULL,
CLI_APELLIDOS VARCHAR2(100) NOT NULL,
CLI_NUMEROS VARCHAR2(24) NOT NULL,
CLI_CONTACTO_ADICIONALES VARCHAR(150),
CLI_FECHA_NACIMIENTO DATE NOT NULL,

CONSTRAINT PK_CLI_ID PRIMARY KEY (CLI_ID)
);

COMMENT ON COLUMN CLIENTE.CLI_ID IS 'Llave primaria de la tabla cliente';
COMMENT ON COLUMN CLIENTE.CLI_NOMBRES IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTE.CLI_APELLIDOS IS 'Apellidos del cliente';
COMMENT ON COLUMN CLIENTE.CLI_NUMEROS IS 'Numero de telefono del cliente';
COMMENT ON COLUMN CLIENTE.CLI_CONTACTO_ADICIONALES IS 'Contacto adicional del cliente,ejemplo: instagram';
COMMENT ON COLUMN CLIENTE.CLI_FECHA_NACIMIENTO IS 'Fecha de nacimiento del cliente';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO CLIENTE
VALUES( SEQ_CLIENTE.NEXTVAL, 'Luis', 'Martinez', '7123-4567', 'Telegram: @luismtz', TO_DATE('2002-08-15','YYYY-MM-DD') );

CREATE TABLE UBICACION_CLIENTE(
UBC_ID NUMBER,
UBI_ID NUMBER,
CLI_ID NUMBER,

CONSTRAINT PK_UBC_ID PRIMARY KEY(UBC_ID),
CONSTRAINT FK_UBI_UBC FOREIGN KEY (UBI_ID) REFERENCES UBICACION(UBI_ID) ON DELETE CASCADE,
CONSTRAINT FK_CLI_UBC FOREIGN KEY (CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN UBICACION_CLIENTE.UBC_ID IS 'Llave primaria de la tabla Ubicacion_Cliente';
COMMENT ON COLUMN UBICACION_CLIENTE.UBI_ID IS 'Llave foranea a la tabla ubicacion';
COMMENT ON COLUMN UBICACION_CLIENTE.CLI_ID IS 'Llave foranea a la tabla Cliente';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_UBICACION_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO UBICACION_CLIENTE
VALUES( SEQ_UBICACION_CLIENTE.NEXTVAL, 1, 1 );

CREATE TABLE CREDENCIALES_CLIENTE(
CRC_ID RAW(16) DEFAULT SYS_GUID(),
CRC_CONTRASENIAS VARCHAR2(264) NOT NULL,
CRC_CORREOS VARCHAR2(150) NOT NULL,
CRC_TOKEN VARCHAR2(6)NULL,
CRC_TOKEN_EXPIRACION DATE,
CLI_ID NUMBER NOT NULL,

CONSTRAINT PK_CRC_ID PRIMARY KEY(CRC_ID),
CONSTRAINT FK_CLI_CRC FOREIGN KEY(CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_ID IS 'Llave primaria de la tabla Credenciales_Cliente, se usa SYS_GUID para tener mejor seguridad';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_CONTRASENIAS IS 'Contraseña de la cuenta del cliente';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_CORREOS IS 'Correo de la cuenta del cliente';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_TOKEN IS 'Token que se usara para recuperar la cuenta y para confirmar el correo electronico al momento de crear una cuenta';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_TOKEN_EXPIRACION IS 'Tiempo de expiracion del token';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CLI_ID IS 'Llave foranea a la tabla Cliente';

/*Ejemplo de insercion*/
INSERT INTO CREDENCIALES_CLIENTE
(CRC_CONTRASENIAS, CRC_CORREOS, CRC_TOKEN, CRC_TOKEN_EXPIRACION, CLI_ID)
VALUES( '123456', 'luismartinez@gmail.com', NULL, NULL, 1 );

CREATE TABLE MATERIALES(
MTR_ID NUMBER,
MTR_NOMBRES VARCHAR2(100) UNIQUE NOT NULL,
CONSTRAINT PK_MTR_ID PRIMARY KEY (MTR_ID)
);

COMMENT ON COLUMN MATERIALES.MTR_ID IS 'Llave primaria de la tabla Materiales';
COMMENT ON COLUMN MATERIALES.MTR_NOMBRES IS 'Nombre del material';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_MATERIALES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO MATERIALES
VALUES( SEQ_MATERIALES.NEXTVAL, 'Algodon' );

CREATE TABLE CATEGORIA_ROPA(
CTR_ID NUMBER,
CTR_NOMBRES VARCHAR2(100) UNIQUE NOT NULL,

CONSTRAINT PK_CTR_ID PRIMARY KEY (CTR_ID)
);

COMMENT ON COLUMN CATEGORIA_ROPA.CTR_ID IS 'Llave primaria de la tabla Categoria_ropa';
COMMENT ON COLUMN CATEGORIA_ROPA.CTR_NOMBRES IS 'Nombre de la categoria de ropa, ejemplo: Camisas';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_CATEGORIA_ROPA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO CATEGORIA_ROPA
VALUES( SEQ_CATEGORIA_ROPA.NEXTVAL, 'Camisa' );

CREATE TABLE CATEGORIA_TEMATICA(
CTT_ID NUMBER,
CTT_NOMBRES VARCHAR2(100) UNIQUE NULL,

CONSTRAINT PK_CTT_ID PRIMARY KEY (CTT_ID)
);

COMMENT ON COLUMN CATEGORIA_TEMATICA.CTT_ID IS 'Llave primaria De la tabla Categoria_Tematica';
COMMENT ON COLUMN CATEGORIA_TEMATICA.CTT_NOMBRES IS 'Nombre de la categoria tematica, ejemplo: Rock';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_CATEGORIA_TEMATICA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO CATEGORIA_TEMATICA
VALUES( SEQ_CATEGORIA_TEMATICA.NEXTVAL, 'Anime' );

CREATE TABLE PRODUCTO (
PRO_ID NUMBER,
PRO_NOMBRES VARCHAR2(150) NOT NULL,
PRO_DESCRIPCIONES VARCHAR(350) NOT NULL,
PRO_STOCK NUMBER CHECK(PRO_STOCK>=0),
PRO_PRECIO_UNIDADES NUMBER(10,2)CHECK(PRO_PRECIO_UNIDADES>=0) NOT NULL,
PRO_DESCUENTO NUMBER(10,2)DEFAULT 0 CHECK(PRO_DESCUENTO>=0) NOT NULL,
PRO_TALLA VARCHAR2(8) NOT NULL,
PRO_ESTADO VARCHAR2(24) NOT NULL,
CTT_ID NUMBER,
CTR_ID NUMBER,
MTR_ID NUMBER NOT NULL,
PRO_IMG VARCHAR(500),

CONSTRAINT PK_PRO_ID PRIMARY KEY(PRO_ID),
CONSTRAINT FK_CTT_PRO FOREIGN KEY(CTT_ID) REFERENCES CATEGORIA_TEMATICA(CTT_ID) ON DELETE CASCADE,
CONSTRAINT FK_CTR_PRO FOREIGN KEY(CTR_ID) REFERENCES CATEGORIA_ROPA(CTR_ID) ON DELETE CASCADE,
CONSTRAINT FK_MTR_PRO FOREIGN KEY(MTR_ID) REFERENCES MATERIALES(MTR_ID) ON DELETE CASCADE,
CONSTRAINT CK_ESTADO CHECK(PRO_ESTADO IN('Activo','Inactivo'))
);

COMMENT ON COLUMN PRODUCTO.PRO_ID IS 'Llave Primaria de la tabla Productos';
COMMENT ON COLUMN PRODUCTO.PRO_NOMBRES IS 'Nombre del producto';
COMMENT ON COLUMN PRODUCTO.PRO_DESCRIPCIONES IS 'Descripcion del producto';
COMMENT ON COLUMN PRODUCTO.PRO_STOCK IS 'Cantidad en stock';
COMMENT ON COLUMN PRODUCTO.PRO_PRECIO_UNIDADES IS 'Precio por unidad';
COMMENT ON COLUMN PRODUCTO.PRO_DESCUENTO IS 'Descuento que le apique al producto';
COMMENT ON COLUMN PRODUCTO.PRO_TALLA IS 'Talla del producto';
COMMENT ON COLUMN PRODUCTO.PRO_ESTADO IS 'Estado del producto, activo es cuando esta a la venta, inactivo es en caso no haya productos en stock o no puedan cumplir con la entrega o elaboracion del producto en ese momoento';
COMMENT ON COLUMN PRODUCTO.CTT_ID IS 'Llave foranea a la tabla Categoria_Tematica';
COMMENT ON COLUMN PRODUCTO.CTR_ID IS 'Llave foranea a la tabla Categoria_Ropa';
COMMENT ON COLUMN PRODUCTO.MTR_ID IS 'Llave foranea a la tabla Materiales';
COMMENT ON COLUMN PRODUCTO.PRO_IMG IS 'Espacio para guardar las imagenes de los productos';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_PRODUCTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO PRODUCTO
VALUES( SEQ_PRODUCTO.NEXTVAL, 'Hoodie Naruto Oversized', 'Sudadera negra estilo oversized con estampado de Naruto', 25, 29.99, 5.00, 'L', 'Activo', 1, 1, 1 );

CREATE TABLE PRODUCTO_GUARDADO(
PRG_ID NUMBER,
PRO_ID NUMBER NOT NULL,
CLI_ID NUMBER NOT NULL,


CONSTRAINT PK_PRG_ID PRIMARY KEY(PRG_ID),
CONSTRAINT FK_PRO_PRG FOREIGN KEY (PRO_ID) REFERENCES PRODUCTO(PRO_ID)ON DELETE CASCADE,
CONSTRAINT FK_CLI_PRG FOREIGN KEY (CLI_ID) REFERENCES CLIENTE(CLI_ID)ON DELETE CASCADE
);

COMMENT ON COLUMN PRODUCTO_GUARDADO.PRG_ID IS 'Llave primaria de la tabla Producto_Guardado';
COMMENT ON COLUMN PRODUCTO_GUARDADO.PRO_ID IS 'Llave foranea a la tabla producto';
COMMENT ON COLUMN PRODUCTO_GUARDADO.CLI_ID IS 'Llave foranea a la tabla Cliente';

/*Secuencia para que en cada insercion aumente el valor de la id*/
CREATE SEQUENCE SEQ_PRODUCTO_GUARDADO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*Ejemplo de insercion*/

INSERT INTO PRODUCTO
VALUES( SEQ_PRODUCTO.NEXTVAL, 'Hoodie Naruto Oversized', 'Sudadera negra estilo oversized con estampado de Naruto', 25, 29.99, 5.00, 'L', 'Activo', 1, 1, 1 );

CREATE TABLE PEDIDO(
PED_ID NUMBER,
PED_FECHAS DATE,
PED_PRECIO_TOTALES NUMBER(10,2) DEFAULT 0 CHECK(PED_PRECIO_TOTALES>=0) NOT NULL,
PED_TOTAL_DESCUENTOS NUMBER(10,2) DEFAULT 0 CHECK(PED_TOTAL_DESCUENTOS>=0) NOT NULL,
PED_ESTADO_COMPRAS VARCHAR2(24)NOT NULL,
PED_SOLICITUDES VARCHAR2(24) NOT NULL,
UBC_ID NUMBER NOT NULL,
USR_ID NUMBER NOT NULL,


CONSTRAINT CK_PED_ESTADO CHECK(PED_ESTADO_COMPRAS IN('Carrito','Pendiente','Aprobado')),
CONSTRAINT CK_PED_SOLICITUD CHECK(PED_SOLICITUDES IN('Pendiente','Aprobado')),
CONSTRAINT PK_PED_ID PRIMARY KEY(PED_ID),
CONSTRAINT FK_UBC_PED FOREIGN KEY(UBC_ID) REFERENCES UBICACION_CLIENTE(UBC_ID) ON DELETE CASCADE,
CONSTRAINT FK_USR_PED FOREIGN KEY(USR_ID) REFERENCES USUARIO(USR_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN PEDIDO.PED_ID IS 'Llave primaria de la tabla pedido';
COMMENT ON COLUMN PEDIDO.PED_FECHAS IS 'Fecha en que se entrega el pedido';
COMMENT ON COLUMN PEDIDO.PED_PRECIO_TOTALES IS 'Precio total del pedido';
COMMENT ON COLUMN PEDIDO.PED_TOTAL_DESCUENTOS IS 'Precio total del pedido aplicando los descuentos';
COMMENT ON COLUMN PEDIDO.PED_ESTADO_COMPRAS IS 'Estado de compra, se utilizara esta misma tabla para el carrito de compras, una vez el cliente confirme la compra debera esperar a que el pedido sea aprovado por un administrador';
COMMENT ON COLUMN PEDIDO.PED_SOLICITUDES IS 'Estado de la solicitud de aprovacion, ya sea aprovado o pendiente';
COMMENT ON COLUMN PEDIDO.UBC_ID IS 'Llave foranea a la tabla Ubicacion';
COMMENT ON COLUMN PEDIDO.USR_ID IS 'Llave foranea a la tabla Usuario';

CREATE TABLE DETALLE_PEDIDO (
DTP_ID NUMBER,
PRO_ID NUMBER NOT NULL,
PED_ID NUMBER NOT NULL,
DTP_CANTIDAD NUMBER NOT NULL,

CONSTRAINT PK_DTP_ID PRIMARY KEY(DTP_ID),
CONSTRAINT FK_PRO_DTP FOREIGN KEY(PRO_ID) REFERENCES PRODUCTO(PRO_ID) ON DELETE CASCADE,
CONSTRAINT FK_PED_DTP FOREIGN KEY(PED_ID) REFERENCES PEDIDO(PED_ID) ON DELETE CASCADE
);


COMMENT ON COLUMN DETALLE_PEDIDO.DTP_ID IS 'Llave primaria de la tabla Detalle_Pedido';
COMMENT ON COLUMN DETALLE_PEDIDO.PRO_ID IS 'Llave foranea a la tabla Productos';
COMMENT ON COLUMN DETALLE_PEDIDO.PED_ID IS 'Llave foranea a la tabla Pedido';
COMMENT ON COLUMN DETALLE_PEDIDO.DTP_CANTIDAD IS 'Cantidad de productos que va a pedir el cliente';

/*Secuencias y triggers para utilizar en la tabla */

CREATE SEQUENCE SEQ_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_DETALLE_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_VALIDAR_CARRITO
BEFORE INSERT ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
    V_ESTADO PEDIDO.PED_ESTADO_COMPRAS%TYPE;
BEGIN
    SELECT PED_ESTADO_COMPRAS
    INTO V_ESTADO
    FROM PEDIDO
    WHERE PED_ID = :NEW.PED_ID;

    IF V_ESTADO <> 'Carrito' THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se pueden agregar productos porque el pedido no esta en estado Carrito');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_TOTAL_PEDIDO
AFTER INSERT ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
    V_PRECIO PRODUCTO.PRO_PRECIO_UNIDADES%TYPE;
    V_DESCUENTO PRODUCTO.PRO_DESCUENTO%TYPE;
BEGIN

    SELECT PRO_PRECIO_UNIDADES, PRO_DESCUENTO
    INTO V_PRECIO, V_DESCUENTO
    FROM PRODUCTO
    WHERE PRO_ID = :NEW.PRO_ID;

    UPDATE PEDIDO
    SET 
        PED_PRECIO_TOTALES = PED_PRECIO_TOTALES + (V_PRECIO * :NEW.DTP_CANTIDAD),

        PED_TOTAL_DESCUENTOS = PED_TOTAL_DESCUENTOS + (V_DESCUENTO * :NEW.DTP_CANTIDAD)

    WHERE PED_ID = :NEW.PED_ID;

END;
/

Select *from Ubicacion_CLiente;

SELECT *FROM producto;
SELECT *FROM PEDIDO; 

/*Ejemplos de inserciones*/

INSERT INTO PEDIDO
VALUES( SEQ_PEDIDO.NEXTVAL, TO_DATE('2026-05-06','YYYY-MM-DD'), 5, 2, 'Carrito', 'Pendiente', 2, 1 );

INSERT INTO DETALLE_PEDIDO
VALUES( SEQ_DETALLE_PEDIDO.NEXTVAL, 1, 10, 2 );