CREATE TABLE ROL(
ROL_id NUMBER,
ROL_nombres VARCHAR2(20) UNIQUE NOT NULL,
CONSTRAINT PK_ROL_ID PRIMARY KEY(ROL_id),
CONSTRAINT NOMBRESROL CHECK(ROL_nombres IN ('Administrador','Empleado','Repartidor'))
);

COMMENT ON COLUMN ROL.ROL_ID IS 'Id del rol';
COMMENT ON COLUMN ROL.ROL_NOMBRES IS 'Nomnbre interno que tendra el rol dentro del sistema';

CREATE TABLE USUARIO(
USR_ID NUMBER,
USR_NOMBRES VARCHAR2(100) NOT NULL,
USR_APELLIDOS VARCHAR2(100) NOT NULL,
USR_CORREOS VARCHAR2(150) UNIQUE NOT NULL,
USR_CONTRASENIAS VARCHAR2(64) NOT NULL,
USR_TOKEN_RECUPERACION VARCHAR2(6)NULL,
USR_TOKEN_EXPIRACION DATE,
ROL_ID NUMBER NOT NULL,

CONSTRAINT PK_USR_ID PRIMARY KEY (USR_ID),
CONSTRAINT FK_ROL_USR FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN USUARIO.USR_ID IS 'Id de cada usuario';
COMMENT ON COLUMN USUARIO.USR_NOMBRES IS 'Nombre del usuario';
COMMENT ON COLUMN USUARIO.USR_APELLIDOS IS 'Apellidos del usuario';
COMMENT ON COLUMN USUARIO.USR_CORREOS IS 'Correo electronico del usuario, sera nesesesario para que pueda iniciar sesion';
COMMENT ON COLUMN USUARIO.USR_CONTRASENIAS IS 'Contraseña unica que tendra el usuario';
COMMENT ON COLUMN USUARIO.USR_TOKEN_RECUPERACION IS 'Token de recuperacion de cuenta';
COMMENT ON COLUMN USUARIO.USR_TOKEN_EXPIRACION IS 'Tiempo de duracion del token de recuperacion';
COMMENT ON COLUMN USUARIO.ROL_ID IS 'Id del rol que tendra el usuario';

CREATE TABLE ENCOMENDISTA(
ENC_ID NUMBER,
ENC_NOMBRES VARCHAR2(50) NOT NULL,
ENC_CONTACTOS VARCHAR2(150) NOT NULL,

CONSTRAINT PK_ENC_ID PRIMARY KEY (ENC_ID)
);

COMMENT ON COLUMN ENCOMENDISTA.ENC_ID IS 'Id del encomendista';
COMMENT ON COLUMN ENCOMENDISTA.ENC_NOMBRES IS 'Nombre de la empresa o entidad que funciona como encomendista';
COMMENT ON COLUMN ENCOMENDISTA.ENC_CONTACTOS IS 'Contacto de el encomendista';

CREATE TABLE UBICACION (
UBI_ID NUMBER,
UBI_DEPARTAMENTOS VARCHAR2(15)NOT NULL,
UBI_MUNICIPIOS VARCHAR2(25) NOT NULL,
UBI_FECHAS DATE NOT NULL,
UBI_HORARIOS VARCHAR2(5) NOT NULL,
ENC_ID NUMBER NOT NULL,

CONSTRAINT PK_UBI_ID PRIMARY KEY (UBI_ID),
CONSTRAINT FK_ENC_UBI FOREIGN KEY (ENC_ID) REFERENCES ENCOMENDISTA(ENC_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN UBICACION.UBI_ID IS 'Id de la ubicacion';
COMMENT ON COLUMN UBICACION.UBI_DEPARTAMENTOS IS 'Departamento em el que se encuentra la direccion ';
COMMENT ON COLUMN UBICACION.UBI_MUNICIPIOS IS 'Municipio en el que se encuentra la direccion';
COMMENT ON COLUMN UBICACION.UBI_FECHAS IS 'Fecha en que se realizan entregas en esa ubicacion';
COMMENT ON COLUMN UBICACION.UBI_HORARIOS IS 'Hora y detalles';
COMMENT ON COLUMN UBICACION.ENC_ID IS 'En caso que en la direccion un encomendista realice la entrega';

CREATE TABLE EVENTO(
EVE_ID NUMBER,
EVE_NOMBRES VARCHAR2(50) NOT NULL,  
EVE_IMGS VARCHAR2 (500),
EVE_ORGANIZADORES VARCHAR2(300) NOT NULL,
UBI_ID NUMBER NOT NULL,

CONSTRAINT PK_EVE_ID PRIMARY KEY(EVE_ID),
CONSTRAINT FK_UBI_EVE FOREIGN KEY (UBI_ID) REFERENCES UBICACION(UBI_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN EVENTO.EVE_ID IS 'Id del evento';
COMMENT ON COLUMN EVENTO.EVE_NOMBRES IS 'Nombre del evento';
COMMENT ON COLUMN EVENTO.EVE_IMGS IS 'Espacio para la imagen promocional del evento';
COMMENT ON COLUMN EVENTO.EVE_ORGANIZADORES IS 'Quienes son los organizadores del evento, ejemplo: El evento es terror cifco, el organizador es cifco';
COMMENT ON COLUMN EVENTO.UBI_ID IS 'Id de la ubicacion en que se realizara el evento';

CREATE TABLE CLIENTE(
CLI_ID NUMBER,
CLI_NOMBRES VARCHAR2(100) NOT NULL,
CLI_APELLIDOS VARCHAR2(100) NOT NULL,
CLI_NUMEROS VARCHAR2(24) NOT NULL,
CLI_CONTACTO_ADICIONALES VARCHAR(150),
CLI_FECHA_NACIMIENTO DATE NOT NULL,
CLI_EDAD NUMBER CHECK(CLI_EDAD >= 18) NOT NULL,

CONSTRAINT PK_CLI_ID PRIMARY KEY (CLI_ID)
);

COMMENT ON COLUMN CLIENTE.CLI_ID IS 'Id del cliente';
COMMENT ON COLUMN CLIENTE.CLI_NOMBRES IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTE.CLI_APELLIDOS IS 'Apellidos del cliente';
COMMENT ON COLUMN CLIENTE.CLI_NUMEROS IS 'Numero de telefono del cliente';
COMMENT ON COLUMN CLIENTE.CLI_CONTACTO_ADICIONALES IS 'Contacto adicional del cliente,ejemplo: instagram';
COMMENT ON COLUMN CLIENTE.CLI_FECHA_NACIMIENTO IS 'Fecha de nacimiento del cliente';
COMMENT ON COLUMN CLIENTE.CLI_EDAD IS 'Edad del cliente';

CREATE TABLE UBICACION_CLIENTE(
UBC_ID NUMBER,
UBI_ID NUMBER,
CLI_ID NUMBER,

CONSTRAINT PK_UBC_ID PRIMARY KEY(UBC_ID),
CONSTRAINT FK_UBI_UBC FOREIGN KEY (UBI_ID) REFERENCES UBICACION(UBI_ID) ON DELETE CASCADE,
CONSTRAINT FK_CLI_UBC FOREIGN KEY (CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN UBICACION_CLIENTE.UBC_ID IS 'Id de la ubicacion del cliente';
COMMENT ON COLUMN UBICACION_CLIENTE.UBI_ID IS 'Id de la ubicacion';
COMMENT ON COLUMN UBICACION_CLIENTE.CLI_ID IS 'Id del cliente';

CREATE TABLE CREDENCIALES_CLIENTE(
CRC_ID RAW(16) DEFAULT SYS_GUID(),
CRC_CONTRASENIAS VARCHAR2(64) NOT NULL,
CRC_CORREOS VARCHAR2(150) NOT NULL,
CRC_TOKEN VARCHAR2(6)NULL,
CRC_TOKEN_EXPIRACION DATE,
CLI_ID NUMBER NOT NULL,

CONSTRAINT PK_CRC_ID PRIMARY KEY(CRC_ID),
CONSTRAINT FK_CLI_CRC FOREIGN KEY(CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_ID IS 'Id de las credenciales del cliente, se usa SYS_GUID para tener mejor seguridad';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_CONTRASENIAS IS 'Contraseña de la cuenta del cliente';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_CORREOS IS 'Correo de la cuenta del cliente';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_TOKEN IS 'Token que se usara para recuperar la cuenta y para confirmar el correo electronico al momento de crear una cuenta';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CRC_TOKEN_EXPIRACION IS 'Tiempo de expiracion del token';
COMMENT ON COLUMN CREDENCIALES_CLIENTE.CLI_ID IS 'Id del cliente';

CREATE TABLE MATERIALES(
MTR_ID NUMBER,
MTR_NOMBRES VARCHAR2(100) UNIQUE NOT NULL,
CONSTRAINT PK_MTR_ID PRIMARY KEY (MTR_ID)
);

COMMENT ON COLUMN MATERIALES.MTR_ID IS 'Id del Material';
COMMENT ON COLUMN MATERIALES.MTR_NOMBRES IS 'Nombre del material';

CREATE TABLE CATEGORIA_ROPA(
CTR_ID NUMBER,
CTR_NOMBRES VARCHAR2(100) UNIQUE NOT NULL,

CONSTRAINT PK_CTR_ID PRIMARY KEY (CTR_ID)
);

COMMENT ON COLUMN CATEGORIA_ROPA.CTR_ID IS 'Id de la categoria';
COMMENT ON COLUMN CATEGORIA_ROPA.CTR_NOMBRES IS 'Nombre de la categoria de ropa, ejemplo: Camisas';

CREATE TABLE CATEGORIA_TEMATICA(
CTT_ID NUMBER,
CTT_NOMBRES VARCHAR2(100) UNIQUE NULL,

CONSTRAINT PK_CTT_ID PRIMARY KEY (CTT_ID)
);

COMMENT ON COLUMN CATEGORIA_TEMATICA.CTT_ID IS 'Id de la categoria';
COMMENT ON COLUMN CATEGORIA_TEMATICA.CTT_NOMBRES IS 'Nombre de la categoria tematica, ejemplo: Rock';

CREATE TABLE PRODUCTO (
PRO_ID NUMBER,
PRO_NOMBRES VARCHAR2(150) NOT NULL,
PRO_DESCRIPCIONES VARCHAR(350) NOT NULL,
PRO_STOCK NUMBER CHECK(PRO_STOCK>=0),
PRO_PRECIO_UNIDADES NUMBER(2,8)CHECK(PRO_PRECIO_UNIDADES>=0) NOT NULL,
PRO_DESCUENTO NUMBER(2,8) CHECK(PRO_DESCUENTO>=0) NOT NULL,
PRO_TALLA VARCHAR2(8) NOT NULL,
PRO_ESTADO VARCHAR2(24) NOT NULL,
CTT_ID NUMBER,
CTR_ID NUMBER,
MTR_ID NUMBER NOT NULL,

CONSTRAINT PK_PRO_ID PRIMARY KEY(PRO_ID),
CONSTRAINT FK_CTT_PRO FOREIGN KEY(CTT_ID) REFERENCES CATEGORIA_TEMATICA(CTT_ID) ON DELETE CASCADE,
CONSTRAINT FK_CTR_PRO FOREIGN KEY(CTR_ID) REFERENCES CATEGORIA_ROPA(CTR_ID) ON DELETE CASCADE,
CONSTRAINT FK_MTR_PRO FOREIGN KEY(MTR_ID) REFERENCES MATERIALES(MTR_ID) ON DELETE CASCADE,
CONSTRAINT CK_ESTADO CHECK(PRO_ESTADO IN('Activo','Inactivo'))
);

COMMENT ON COLUMN PRODUCTO.PRO_ID IS 'Id del producto';
COMMENT ON COLUMN PRODUCTO.PRO_NOMBRES IS 'Nombre del producto';
COMMENT ON COLUMN PRODUCTO.PRO_DESCRIPCIONES IS 'Descripcion del producto';
COMMENT ON COLUMN PRODUCTO.PRO_STOCK IS 'Cantidad en stock';
COMMENT ON COLUMN PRODUCTO.PRO_PRECIO_UNIDADES IS 'Precio por unidad';
COMMENT ON COLUMN PRODUCTO.PRO_DESCUENTO IS 'Descuento que le apique al producto';
COMMENT ON COLUMN PRODUCTO.PRO_TALLA IS 'Talla del producto';
COMMENT ON COLUMN PRODUCTO.PRO_ESTADO IS 'Estado del producto, activo es cuando esta a la venta, inactivo es en caso no haya productos en stock o no puedan cumplir con la entrega o elaboracion del producto en ese momoento';
COMMENT ON COLUMN PRODUCTO.CTT_ID IS 'Id de la Categoria temarica ';
COMMENT ON COLUMN PRODUCTO.CTR_ID IS 'Id de la categoria de ropa';
COMMENT ON COLUMN PRODUCTO.MTR_ID IS 'Id de el material con que esta hecho el producto';

CREATE TABLE PRODUCTO_GUARDADO(
PRG_ID NUMBER,
PRO_ID NUMBER NOT NULL,
CLI_ID NUMBER NOT NULL,


CONSTRAINT PK_PRG_ID PRIMARY KEY(PRG_ID),
CONSTRAINT FK_PRO_PRG FOREIGN KEY (PRO_ID) REFERENCES PRODUCTO(PRO_ID)ON DELETE CASCADE,
CONSTRAINT FK_CLI_PRG FOREIGN KEY (CLI_ID) REFERENCES CLIENTE(CLI_ID)ON DELETE CASCADE
);

COMMENT ON COLUMN PRODUCTO_GUARDADO.PRG_ID IS 'Id del registro';
COMMENT ON COLUMN PRODUCTO_GUARDADO.PRO_ID IS 'Id del producto que el cliente va a guardar';
COMMENT ON COLUMN PRODUCTO_GUARDADO.CLI_ID IS 'Id del cliente que guarda el producto';

CREATE TABLE PEDIDO(
PED_ID NUMBER,
PED_FECHAS DATE,
PED_PRECIO_TOTALES NUMBER(2,8) CHECK(PED_PRECIO_TOTALES>=0) NOT NULL,
PED_TOTAL_DESCUENTOS NUMBER(2,8) CHECK(PED_TOTAL_DESCUENTOS>=0) NOT NULL,
PED_ESTADO_COMPRAS VARCHAR2(24)NOT NULL,
PED_SOLICITUDES VARCHAR2(24) NOT NULL,
UBC_ID NUMBER NOT NULL,
USR_ID NUMBER NOT NULL,


CONSTRAINT CK_PED_ESTADO CHECK(PED_ESTADO_COMPRAS IN('Carrito','Pendiente','Aprobado')),
CONSTRAINT CK_PED_SOLICITUD CHECK(PED_SOLICITUDES IN('Pendiente','Aprobado')),
CONSTRAINT PK_PED_ID PRIMARY KEY(PED_ID),
CONSTRAINT FK_UBC_PED FOREIGN KEY(UBC_ID) REFERENCES UBICACION_CLIENTE(UBC_ID) ON DELETE CASCADE,
CONSTRAINT FK_USR_PED FOREIGN KEY(USR_ID) REFERENCES USUARIO(USR_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN PEDIDO.PED_ID IS 'Id del pedido';
COMMENT ON COLUMN PEDIDO.PED_FECHAS IS 'Fecha en que se entrega el pedido';
COMMENT ON COLUMN PEDIDO.PED_PRECIO_TOTALES IS 'Precio total del pedido';
COMMENT ON COLUMN PEDIDO.PED_TOTAL_DESCUENTOS IS 'Precio total del pedido aplicando los descuentos';
COMMENT ON COLUMN PEDIDO.PED_ESTADO_COMPRAS IS 'Estado de compra, se utilizara esta misma tabla para el carrito de compras, una vez el cliente confirme la compra debera esperar a que el pedido sea aprovado por un administrador';
COMMENT ON COLUMN PEDIDO.PED_SOLICITUDES IS 'Estado de la solicitud de aprovacion, ya sea aprovado o pendiente';
COMMENT ON COLUMN PEDIDO.UBC_ID IS 'Id de la ubicacion de entrega';
COMMENT ON COLUMN PEDIDO.USR_ID IS 'Id del usuario que aprovo el pedido';

CREATE TABLE DETALLE_PEDIDO (
DTP_ID NUMBER,
PRO_ID NUMBER NOT NULL,
PED_ID NUMBER NOT NULL,

CONSTRAINT PK_DTP_ID PRIMARY KEY(DTP_ID),
CONSTRAINT FK_PRO_DTP FOREIGN KEY(PRO_ID) REFERENCES PRODUCTO(PRO_ID) ON DELETE CASCADE,
CONSTRAINT FK_PED_DTP FOREIGN KEY(PED_ID) REFERENCES PEDIDO(PED_ID) ON DELETE CASCADE
);


COMMENT ON COLUMN DETALLE_PEDIDO.DTP_ID IS 'Id del detalle pedido';
COMMENT ON COLUMN DETALLE_PEDIDO.PRO_ID IS 'Id de los productos';
COMMENT ON COLUMN DETALLE_PEDIDO.PED_ID IS 'Id del pedido al que pertenece el detalle pedido';